services:

  postgres:
    image: postgres:15
    container_name: swift_postgres
    environment:
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swift
      POSTGRES_DB: swifttrack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swift"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: swift_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: swift
      RABBITMQ_DEFAULT_PASS: swift
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  order-service:
    build: ./order-service
    container_name: order_service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://swift:swift@postgres:5432/swifttrack
      RABBITMQ_URL: amqp://swift:swift@rabbitmq:5672/
    ports:
      - "8000:8000"
    volumes:
      - ./order-service/app:/app/app

  cms-adapter:
    build: ./cms-adapter
    container_name: cms_adapter
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://swift:swift@rabbitmq:5672/
    volumes:
      - ./cms-adapter/app:/app/app

  ros-adapter:
    build: ./ros-adapter
    container_name: ros_adapter
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://swift:swift@rabbitmq:5672/
    volumes:
      - ./ros-adapter/app:/app/app

  wms-adapter:
    build: ./wms-adapter
    container_name: wms_adapter
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://swift:swift@rabbitmq:5672/
    volumes:
      - ./wms-adapter/app:/app/app

  notification:
    build: ./notification-service
    container_name: notification_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8001"
    environment:
      RABBITMQ_URL: amqp://swift:swift@rabbitmq:5672/
    volumes:
      - ./notification-service/app:/app/app

volumes:
  pgdata: